apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: 747533830207.dkr.ecr.ap-south-1.amazonaws.com/dotnet:latest  # Update with your image URL
        ports:
        - containerPort: 80  # Update with the appropriate port

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-service
spec:
  selector:
    app: dotnet-app
  ports:
  - protocol: TCP
    port: 80  # Update with the appropriate port
    targetPort: 80  # Update with the container port
  type: LoadBalancer  # Update with the desired service type
